name: Deploy FastAPI to Vercel (or Render/Other)

on:
  push:
    branches:
      - main  # Deploys on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        pytest || echo "Tests failed but continuing deployment"

    - name: Deploy to Vercel (or other platform)
      run: |
        vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
